### ISSUE TITLE
Unhandled error

### ISSUE THREAD

**Issue by kpgarrod** [firebase/flashlight#1]
I got this while doing a mass delete:

events.js:72
throw er; // Unhandled 'error' event
^
Error: socket hang up
at createHangUpError (http.js:1473:15)
at Socket.socketOnEnd [as onend] (http.js:1569:23)
at Socket.g (events.js:175:14)
at Socket.EventEmitter.emit (events.js:117:20)
at _stream_readable.js:920:16
at process._tickCallback (node.js:415:13)

**Comment by katowulf** [comment]
Should be resolved now that we've switched to the official ES node client. We could probably still do some error recovering in process.on('uncaughtException') but I guess I'd rather leave this up to a monitoring tool.
