### ISSUE TITLE
TypeError: Cannot read property 'hasOwnProperty' of undefined.

### ISSUE THREAD

**Issue by idanb11** [firebase/flashlight#38]
```
function ac(a){try{a()}catch(b){setTimeout(function(){throw b;},Math.floor(0))
                                                            ^
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Object.SearchQueue._process (c:\Users\Idanb11\Work\maptiv8-firebase\flashlight\lib\SearchQueue.js:22:29)
    at c:\Users\Idanb11\Work\maptiv8-firebase\flashlight\node_modules\firebase\lib\firebase-node.js:94:979
    at ac (c:\Users\Idanb11\Work\maptiv8-firebase\flashlight\node_modules\firebase\lib\firebase-node.js:44:20)
    at Td (c:\Users\Idanb11\Work\maptiv8-firebase\flashlight\node_modules\firebase\lib\firebase-node.js:94:965)
    at Rd.Eb (c:\Users\Idanb11\Work\maptiv8-firebase\flashlight\node_modules\firebase\lib\firebase-node.js:94:908)
    at Ud.Eb (c:\Users\Idanb11\Work\maptiv8-firebase\flashlight\node_modules\firebase\lib\firebase-node.js:95:417)
    at c:\Users\Idanb11\Work\maptiv8-firebase\flashlight\node_modules\firebase\lib\firebase-node.js:110:469
    at c:\Users\Idanb11\Work\maptiv8-firebase\flashlight\node_modules\firebase\lib\firebase-node.js:62:1194
    at Wb (c:\Users\Idanb11\Work\maptiv8-firebase\flashlight\node_modules\firebase\lib\firebase-node.js:58:222)
    at R (c:\Users\Idanb11\Work\maptiv8-firebase\flashlight\node_modules\firebase\lib\firebase-node.js:62:1171)
```

**Comment by jcbeaury** [comment]
Try updating the npm firebase version in package.json. I was getting a very similar error, and I updated from the default (~1.0.1-npm) to the most recent (~2.2.9-npm) and it was fixed! Hope this helps.

**Comment by IVLMediaInc** [comment]
We're experiencing the same issue, even after upgrading npm firebase to 2.2.9 as well

**Comment by dougamos** [comment]
I'm having the same issue. firebase npm module is at 2.2.9 for me

**Comment by katowulf** [comment]
Comments which do not contribute anything new to the issue will be deleted unanswered. A minimal repro and a stack trace are the fastest way to resolution.

**Comment by dougamos** [comment]
I had the same stacktrace because the data I pushed to search/request was malformed.

The following data caused the script to exit with the above stacktrace
```
{
  "search" {
    "request" : {
      "index" : "index",
      "query" : {
        "query_string" : {
          "query" : "bob"
        }
      },
      "type" : "user"
    }
  }
}
```

The following data did not:

```
{
  "search" {
    "request" : {
      "-KCu3UCzIXvzc2ZxzkFC": {
        "index" : "index",
        "query" : {
          "query_string" : {
            "query" : "bob"
          }
        },
        "type" : "user"
      }
    }
  }
}
```

**Comment by katowulf** [comment]
See the [security rules in our example](https://github.com/firebase/flashlight/blob/master/example/seed/security_rules.json). Add rules to prevent malformed requests. PRs to produce better error messages welcome.
