### ISSUE TITLE
ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by gosmik** [firebase/flashlight#79]
I did run on windows
$ node example.js
C:\wamp\www\flashlight\example\example.js:85
})(jQuery);
   ^

ReferenceError: jQuery is not defined
    at Object.<anonymous> (C:\wamp\www\flashlight\example\example.js:85:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by katowulf** [comment]
It's [included here in the example](https://github.com/firebase/flashlight/blob/master/example/index.html#L71). Something must have changed in your local code, or jquery is being excluded (maybe by your adblock software?).
